### ISSUE TITLE
Import Project with "Attach Standard Sources"

### ISSUE THREAD

**Issue by fibsifan** [epam/sap-commerce-intellij-idea-plugin#1025]
Hello,

I'm on version 2023.3.5 and might have found a bug. I imported a project and selected the "Attach Standard Source (e.g. Backoffice)" during project import.

I then looked at some of the standard modules that come with source code, e.g. acceleratorcms. It looks like this:
![grafik](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/574988/326cd0fa-d1ef-4468-a89c-7d0da88c4cae)

I would have expected that the source folders are configured (including gensrc as generated):
![grafik](https://github.com/epam/sap-commerce-intellij-idea-plugin/assets/574988/93e8da20-c079-4468-95f7-6e7cca287a28)

Feel free to close this issue if I mixed up features or this is already fixed in the upcoming version.

**Comment by mlytvyn** [comment]
@fibsifan thank you for sharing your feedback.

original idea of the project import was related to faster project build / import and that's why there is a flag "import OOTB modules in read-only mode"

so, there are two modes:
1. Import OOTB in readonly mode - FALSE

In this mode almost all OOTB extensions will not get `src` / `gensrc` folders registered as IntelliJ IDEA sources.

3. Import OOTB in readonly mode - TRUE

All OOTB extensions will get own module library which will have sources attached, so actually there is a respect for "attach sources".

There are few special notes, SAP CC is not shipped with the sources to all extensions, some of them are in the `docs` folder,  some have no `src` dirs at all.

As a summary - most probably `src` dirs will never be registered as IntelliJ IDEA sources as IDEA's default compilation mechanism collides with the SAP CC one and its replication 1-to-1 is not feasible.

**Comment by fibsifan** [comment]
Oh yes I see, IntelliJ would probably try compiling the standard sources and messing with the ant build.

And I found the library configuration, so it looks good, I think. Closing the issue (hope that's okay)

**Comment by mlytvyn** [comment]
@fibsifan If I will find a free minute I will try to document it better in our GitHub wiki!

I fully understand your confusion, when I started maintaining the plugin I was confused a lot and in many areas.
